name: build test and lint

on: [push]

# jobs:
#   deps: 
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Setup Node
#       uses: actions/setup-node@v1
#       with:
#         node-version: 10

#     - name: Cache node modules
#       uses: actions/cache@v1
#       with:
#         path: node_modules
#         key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-deps-${{ env.cache-name }}-
#           ${{ runner.os }}-deps-
#           ${{ runner.os }}-

#     - name: Get deps
#       runs: yarn install --frozen-lockfile



jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v1
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: get deps
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: test
      run: yarn test

    - name: lint
      run: yarn lint

    - name: build
      run: yarn build-prod

      env:
        CI: true
