name: Test, lint, build and deploy

on: [push]

jobs:
  deps:
    
    container: node:10

    steps:    
    - uses: actions/checkout@v1
    
    - name: deps
      run: npm ci 

      env:
        CI: true
